services:
  postgres:
    image: postgres:16
    container_name: pulseapi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pulseapi
      POSTGRES_USER: pulseapi_user
      POSTGRES_PASSWORD: pulseapi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: